replicaCount: 1

fullnameOverride: ""

image:
  repository: ollama/ollama
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 11434

persistence:
  enabled: true
  size: 4Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# ... (other configurations)

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: llama.promptengineers.ai
      paths:
        - path: /
          pathType: Prefix
  tls: []
